#!/bin/bash
# ══════════════════════════════════════════════════════════
#  🧠 NullVector v3.0 — Pterodactyl Startup Script
#
#  Designed for HidenCloud / Pterodactyl panel.
#  Set this as your startup command in the egg configuration.
#
#  Environment Variables (set in Pterodactyl Startup tab):
#    DISCORD_TOKEN    — Your bot token (REQUIRED)
#    POLLINATIONS_KEY — Pollinations API key
#    ADMIN_IDS        — Comma-separated admin Discord user IDs
#    BOT_PREFIX       — Command prefix (default: !)
#    AUTO_UPDATE      — Set to 1 to git pull on startup
#    GIT_ADDRESS      — Git repo URL to clone
# ══════════════════════════════════════════════════════════

cd /home/container

# ── Colors ────────────────────────────────────────────────
RED='\033[91m'
GREEN='\033[92m'
YELLOW='\033[93m'
BLUE='\033[94m'
PURPLE='\033[95m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

echo ""
echo -e "${PURPLE}${BOLD}    ╔══════════════════════════════════════════╗"
echo -e "    ║  🧠 NullVector v3.0 — Starting... 🧠  ║"
echo -e "    ║       Smart AI Assistant                  ║"
echo -e "    ╚══════════════════════════════════════════╝${RESET}"
echo ""

# ── Step 1: Clone or update from Git ─────────────────────
if [[ -n "${GIT_ADDRESS}" ]]; then
    echo -e "${BLUE}${BOLD}── Cloning/Updating from Git ──${RESET}"

    if [[ -d .git ]]; then
        if [[ "${AUTO_UPDATE}" == "1" ]]; then
            echo -e "  ${DIM}Pulling latest changes...${RESET}"
            git pull
            echo -e "  ${GREEN}✓${RESET} Pulled latest changes"
        else
            echo -e "  ${YELLOW}⚠${RESET} Auto-update disabled. Using existing code."
        fi
    else
        echo -e "  ${DIM}Cloning ${GIT_ADDRESS}...${RESET}"
        git clone "${GIT_ADDRESS}" /home/container/repo
        if [[ -d /home/container/repo ]]; then
            cp -r /home/container/repo/* /home/container/
            cp -r /home/container/repo/.* /home/container/ 2>/dev/null
            rm -rf /home/container/repo
            echo -e "  ${GREEN}✓${RESET} Cloned repository"
        fi
    fi
fi

# ── Step 2: Install Python dependencies ──────────────────
echo -e "\n${BLUE}${BOLD}── Installing Dependencies ──${RESET}"

if [[ -f /home/container/requirements.txt ]]; then
    pip install -U --prefix .local -r /home/container/requirements.txt
    echo -e "  ${GREEN}✓${RESET} Installed from requirements.txt"
else
    echo -e "  ${YELLOW}⚠${RESET} No requirements.txt found"
fi

# Make sure .local packages are in the Python path
export PYTHONPATH="/home/container/.local/lib/python3.12/site-packages:${PYTHONPATH}"

# ── Step 3: Create data directory ────────────────────────
echo -e "\n${BLUE}${BOLD}── Setting Up Data Directory ──${RESET}"

mkdir -p /home/container/data
echo -e "  ${GREEN}✓${RESET} Data directory ready"

# ── Step 4: Create .env from environment variables ───────
echo -e "\n${BLUE}${BOLD}── Configuring Environment ──${RESET}"

cat > /home/container/.env << EOF
# NullVector v3.0 — Auto-generated by Pterodactyl startup
# Pterodactyl env vars take priority over this file

DISCORD_TOKEN=${DISCORD_TOKEN:-}
POLLINATIONS_KEY=${POLLINATIONS_KEY:-}
POLLINATIONS_BASE_URL=${POLLINATIONS_BASE_URL:-https://gen.pollinations.ai}
POLLINATIONS_MEDIA_URL=${POLLINATIONS_MEDIA_URL:-https://media.pollinations.ai}
ADMIN_IDS=${ADMIN_IDS:-}
BOT_PREFIX=${BOT_PREFIX:-!}
DEFAULT_TEXT_MODEL=${DEFAULT_TEXT_MODEL:-openai-fast}
DEFAULT_IMAGE_MODEL=${DEFAULT_IMAGE_MODEL:-sana}

RATE_LIMIT_HOURLY=${RATE_LIMIT_HOURLY:-30}
RATE_LIMIT_DAILY=${RATE_LIMIT_DAILY:-100}
STM_MESSAGES=${STM_MESSAGES:-8}
LTM_SUMMARY_THRESHOLD=${LTM_SUMMARY_THRESHOLD:-6}
MAX_MEMORY=${MAX_MEMORY:-50}
EOF

echo -e "  ${GREEN}✓${RESET} .env file configured"

# ── Step 5: Validate ─────────────────────────────────────
echo -e "\n${BLUE}${BOLD}── Validating ──${RESET}"

if [[ -z "${DISCORD_TOKEN}" ]]; then
    echo -e "  ${RED}✗${RESET} DISCORD_TOKEN is not set! Add it in the Startup tab."
    echo -e "  ${YELLOW}⚠${RESET} NullVector will NOT start without a token."
fi

if [[ -f /home/container/bot.py ]]; then
    echo -e "  ${GREEN}✓${RESET} bot.py found"
else
    echo -e "  ${RED}✗${RESET} bot.py not found!"
fi

# ── Step 6: Start NullVector! ────────────────────────────
echo ""
echo -e "${PURPLE}${BOLD}    🧠 Starting NullVector v3.0...${RESET}"
echo -e "    ${DIM}Smart Model Routing | Cost-Conscious AI | Sana Sprint Images${RESET}"
echo ""

exec /usr/local/bin/python /home/container/bot.py
